CREATE DATABASE bookee;
CREATE USER my_user WITH PASSWORD 'my_password';
\c bookee

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO my_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to my_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to my_user;
